/**
 * HTML document shell for SSG pages
 * Uses template literal - Preact only renders body content
 */

export interface PageOptions {
	title: string;
	description?: string;
	cssFiles: string[];
	/**
	 * Pre-escaped HTML markup for the document body.
	 *
	 * SECURITY: This value is inserted into the HTML without additional escaping.
	 * It MUST only contain HTML generated by a trusted renderer (e.g. Preact's
	 * render() function) and MUST NOT include untrusted, unescaped user input.
	 */
	body: string;
	/**
	 * JavaScript code to include in a script tag.
	 *
	 * SECURITY: This value is inserted directly into a <script> tag without escaping.
	 * It MUST only contain trusted, developer-controlled JavaScript code and
	 * MUST NOT include any user input or externally-sourced content.
	 */
	scripts?: string;
}

/**
 * Escape HTML special characters to prevent XSS
 */
export function escapeHtml(str: string): string {
	return str
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;');
}

/**
 * Render a complete HTML document
 */
export function renderDocument(options: PageOptions): string {
	const { title, description, cssFiles, body, scripts } = options;

	const cssLinks = cssFiles
		.map(href => `<link rel="stylesheet" href="${escapeHtml(href)}">`)
		.join('\n\t');

	const metaDesc = description
		? `<meta name="description" content="${escapeHtml(description)}">`
		: '';

	return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	${metaDesc}
	<title>${escapeHtml(title)}</title>
	${cssLinks}
</head>
<body>
	${body}
	${scripts ? `<script>${scripts}</script>` : ''}
</body>
</html>`;
}
